name : OptoTransport
channels:
  - conda-forge
  - pypi
dependencies:
  - python
  - pandas
  - pyyaml
  - scipy
  - matplotlib
  - h5py
  - numpy
  - imageio
  - ipykernel
  - sqlalchemy
  - flask-sqlalchemy
  - python-pptx

